#82 upgrade compiler to C++17

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,139 +1,94 @@
-
 language: cpp
+os: linux
+dist: trusty
+sudo: false
 
-# sources  list: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json,
-# packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
+env:
+  global:
+    - DEPS_DIR="${HOME}/deps"
+    - LOCAL_USR_DIR="${HOME}/local"
+    - CMAKE_VERSION=default
+    - BOOST_VERSION=1.67.0
+
+cache:
+  ccache: false
+  directories:
+    - ${DEPS_DIR}
 
 matrix:
   include:
-    - os: linux
-      compiler: gcc
-      addons:
-        apt:
-          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
-          packages: [ 'g++-5', 'libstdc++-5-dev', 'cmake' ]
-      env: CMAKE_BUILD_TYPE=Debug BOOST_VERSION=1.60.0 BOOST_BUILD=true
+    - name: "Debug"
+      env: CMAKE_OPTIONS='-DCMAKE_BUILD_TYPE=Debug' MATRIX_EVAL="export CC='gcc-7' CXX='g++-7'"
+      addons: { apt: { packages: [cmake, cmake-data, 'g++-7'], sources: [ubuntu-toolchain-r-test] } }
 
-    - os: linux
-      compiler: gcc
-      addons:
-        apt:
-          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
-          packages: [ 'g++-5', 'libstdc++-5-dev', 'cmake' ]
-      env: CMAKE_BUILD_TYPE=Release BOOST_VERSION=1.60.0 BOOST_BUILD=true
+    - name: "Release"
+      env: CMAKE_OPTIONS='-DCMAKE_BUILD_TYPE=Release' MATRIX_EVAL="export CC='gcc-7' CXX='g++-7'"
+      addons: { apt: { packages: [cmake, cmake-data, 'g++-7'], sources: [ubuntu-toolchain-r-test] } }
 
-#    - os: linux
-#      compiler: clang
-#      addons:
-#        apt:
-#          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
-#          packages: [ 'libstdc++-5-dev', 'cmake' ]
-#      env: CMAKE_BUILD_TYPE=Debug BOOST_VERSION=1.60.0 BOOST_BUILD=true
-#
-#    - os: linux
-#      compiler: clang
-#      addons:
-#        apt:
-#          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
-#          packages: [ 'libstdc++-5-dev', 'cmake' ]
-#      env: CMAKE_BUILD_TYPE=Release BOOST_VERSION=1.60.0 BOOST_BUILD=true
-
-# container-based builds
-sudo: false
-cache:
-  directories:
-  - $HOME/.ccache
-  #- $HOME/download
-  - ${TRAVIS_BUILD_DIR}/deps/boost-1.60.0
+before_install:
+  - set -e; # fail on the first error
+  - eval "${MATRIX_EVAL}"
+  - |
+    echo "before_install: CC=${CC} CXX=${CXX}"
+    ${CC} -v
+    ${CXX} -v
+    cmake --version
 
 install:
-  ############################################################################
-  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
-  ############################################################################
-  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
-  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
-  - mkdir -p latest-gcc-symlinks
-  - env
+  ### Folders ###
+  - mkdir -p "${DEPS_DIR}"
+
+  ### CMake ###
   - |
-   if [[ "$CXX" = "g++" ]]; then
-       export CXX="g++-5" CC="gcc-5" BOOST_TOOLSET=gcc;
-       export CXXFLAGS="--param ggc-min-expand=20 --param ggc-min-heapsize=512000"
-       ln -s /usr/bin/${CXX} latest-gcc-symlinks/g++
-       ln -s /usr/bin/${CC} latest-gcc-symlinks/gcc
-   fi
-  - |
-   if [[ "$CXX" = "clang++" ]]; then
-       export BOOST_TOOLSET=clang;
-       ln -s /usr/bin/${CXX} latest-gcc-symlinks/clang++
-       ln -s /usr/bin/${CC} latest-gcc-symlinks/clang
-   fi
-  - export PATH=$PWD/latest-gcc-symlinks:$PATH
-  # Install newer boost compatible with gcc 5.
-  ############################################################################
-  # Install Boost headers
-  ############################################################################
-  - |
-    if [[ "${BOOST_VERSION}" != "" ]]; then
-      BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
-      if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
-        if [[ "${BOOST_VERSION}" == "trunk" ]]; then
-          BOOST_URL="http://github.com/boostorg/boost.git"
-          travis_retry git clone --depth 1 --recursive --quiet ${BOOST_URL} ${BOOST_DIR} || exit 1
-          (cd ${BOOST_DIR} && ./bootstrap.sh && ./b2 headers)
-        else
-          ##BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
-          BOOST_URL="http://venediktov.github.io/boost_${BOOST_VERSION//\./_}.tar.gz"
-          mkdir -p ${BOOST_DIR}
-          ##{ travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
-          { travis_retry wget  -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
+    if [[ ${CMAKE_VERSION} != 'default' ]]; then
+        CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.*}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
+        CMAKE_DIR="${DEPS_DIR}/cmake-${CMAKE_VERSION}"
+
+        mkdir -p "${CMAKE_DIR}"
+        if [[ -z "$(ls -A ${CMAKE_DIR})" ]]; then
+            travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C "${CMAKE_DIR}"
         fi
-      fi
-      CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
-      export CMAKE_OPTIONS
+
+        export PATH="${CMAKE_DIR}/bin:${PATH}"
     fi
 
-  ############################################################################
-  # Install Boost.Build
-  ############################################################################
-  - |
-    if [[ "${BOOST_BUILD}" == "true" ]]; then
-      ##(cd ${BOOST_DIR}/tools/build && ./bootstrap.sh --with-toolset=${BOOST_TOOLSET} --with-libraries=program_options,system,filesystem,regex,serialization,log,unit_test_framework && ./b2 toolset=${BOOST_TOOLSET} install --prefix=${DEPS_DIR}/b2)
-      (echo "using gcc : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" > ~/user-config.jam)
-      (echo "using clang : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" >> ~/user-config.jam)
-      (cd ${BOOST_DIR} && ./bootstrap.sh --with-toolset=${BOOST_TOOLSET} --with-libraries=program_options,system,regex,serialization,log,date_time,test && ./b2 toolset=${BOOST_TOOLSET} install --prefix=${BOOST_DIR})
-      #export PATH=${DEPS_DIR}/b2/bin:${PATH}
-      export PATH=${BOOST_DIR}/bin:${PATH}
-    fi
+    export CMAKE_OPTIONS+=" -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} -DCMAKE_RULE_MESSAGES:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON"
 
-  ############################################################################
-  # Install a recent CMake
-  ############################################################################
+  ### Boost ###
   - |
-    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
-      CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
-      mkdir  cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
-      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
-    else
-      brew install cmake
-      brew upgrade cmake
+    if [[ ${BOOST_VERSION} != 'default' ]]; then
+        BOOST_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//\./_}.tar.gz"
+        BOOST_DIR="${DEPS_DIR}/boost-${BOOST_VERSION}"
+        BOOST_TOOLSET=gcc
+        BOOST_LIBS='program_options,system,regex,serialization,log,date_time,test'
+
+        mkdir -p "${BOOST_DIR}"
+        if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
+            BOOST_BUILD_DIR="${HOME}/boost-build"
+            mkdir -p "${BOOST_BUILD_DIR}"
+            travis_retry wget --no-check-certificate --quiet -O - "${BOOST_URL}" | tar --strip-components=1 -xz -C "${BOOST_BUILD_DIR}"
+            cd "${BOOST_BUILD_DIR}"
+            ./bootstrap.sh --with-libraries="${BOOST_LIBS}" --with-toolset="${BOOST_TOOLSET}"
+            ./b2 -d0 -q toolset="${BOOST_TOOLSET}" variant=release link=shared threading=multi runtime-link=shared install --prefix="${BOOST_DIR}"
+        fi
+
+        CMAKE_OPTIONS+=" -DBOOST_ROOT='${BOOST_DIR}'"
     fi
 
 before_script:
-  - ccache -V && ccache --show-stats && ccache --zero-stats
-  #- 'echo "using gcc : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" > ~/user-config.jam'
-  #- 'echo "using clang : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" >> ~/user-config.jam'
-  #- cd "$BOOST_ROOT"; ./b2 toolset="$BOOST_TOOLSET" threading=multi --prefix="$BOOST_DIR" -d0 install
+  - (ccache -V && ccache --show-stats && ccache --zero-stats)
+  - (mkdir -p "${TRAVIS_BUILD_DIR}/Build" && cd "${TRAVIS_BUILD_DIR}/Build" && cmake .. ${CMAKE_OPTIONS})
 
 script:
-  - $CXX --version
-  - cmake --version
-  ############################################################################
-  # Go back to the root of the project and setup the build directory
-  ############################################################################
-  - cd ${TRAVIS_BUILD_DIR}
-  - (mkdir build-vanilla && cd build-vanilla && cmake .. ${CMAKE_OPTIONS})
-  - (cd build-vanilla && make -j4 VERBOSE=1)
-  - cmake --build build-vanilla --target unit-test -- BOOST_TEST_LOG_LEVEL=all
+  - |
+    echo "script: CC=${CC} CXX=${CXX}"
+    ${CC} -v
+    ${CXX} -v
+    cmake --version
+
+  - (cmake --build "${TRAVIS_BUILD_DIR}/Build" -- --no-print-directory -j$(nproc))
+  - (cmake --build "${TRAVIS_BUILD_DIR}/Build" --target unit-test -- --no-print-directory -j$(nproc))
+
+after_script:
+  - set -e
   - ccache --show-stats
-
-
